apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: gateway
  labels:
    app: gateway
    release: monitoring
spec:
  selector:
    matchLabels:
      app: gateway
  namespaceSelector:
    matchNames:
      - app
  endpoints:
    - port: http
      interval: 15s
      path: /metrics 