apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gateway
  namespace: app
  labels:
    app: gateway
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: gateway.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: gateway
                port:
                  number: 80 