apiVersion: v2
name: app
description: A Helm chart for the microservices application
type: application
version: 0.1.0
appVersion: "1.0.0"
dependencies:
  - name: gateway
    version: 0.1.0
    repository: file://../gateway
  - name: auth-service
    version: 0.1.0
    repository: file://../auth-service
  - name: data-service
    version: 0.1.0
    repository: file://../data-service 