apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: microservices-alerts
  namespace: monitoring
  labels:
    app: microservices
    release: monitoring
spec:
  groups:
  - name: microservices
    rules:
    - alert: HighErrorRate
      expr: rate(http_requests_total{namespace="app", status=~"5.."}[5m]) / rate(http_requests_total{namespace="app"}[5m]) > 0.05
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: High error rate detected
        description: Error rate is above 5% for the last 5 minutes

    - alert: PodRestarting
      expr: increase(kube_pod_container_status_restarts_total{namespace="app"}[1h]) > 0
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: Pod is restarting
        description: Pod {{ $labels.pod }} has restarted in the last hour

    - alert: HighMemoryUsage
      expr: container_memory_usage_bytes{namespace="app"} / container_spec_memory_limit_bytes{namespace="app"} > 0.85
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: High memory usage
        description: Container {{ $labels.container }} in pod {{ $labels.pod }} is using more than 85% of its memory limit

    - alert: HighCPUUsage
      expr: rate(container_cpu_usage_seconds_total{namespace="app"}[5m]) / container_spec_cpu_quota{namespace="app"} > 0.85
      for: 5m
      labels:
        severity: warning
      annotations:
        summary: High CPU usage
        description: Container {{ $labels.container }} in pod {{ $labels.pod }} is using more than 85% of its CPU limit 