apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-service
  labels:
    app: data-service
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: data-service
  template:
    metadata:
      labels:
        app: data-service
    spec:
      serviceAccountName: data-service
      containers:
        - name: data-service
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          args: ["-text", "Data service is running"]
          ports:
            - containerPort: 5678
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            httpGet:
              path: /
              port: 5678
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 5678
            initialDelaySeconds: 5
            periodSeconds: 5
          env:
            - name: MINIO_ENDPOINT
              value: {{ .Values.minio.endpoint }}
            - name: MINIO_BUCKET
              value: {{ .Values.minio.bucket }}
            - name: MINIO_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: accesskey
            - name: MINIO_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: minio-credentials
                  key: secretkey 