{{- if .Values.networkPolicy.enabled -}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: data-service
  labels:
    app: data-service
spec:
  podSelector:
    matchLabels:
      app: data-service
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: auth-service
      ports:
        - protocol: TCP
          port: 80
  egress:
    - to:
        - namespaceSelector:
            matchLabels:
              kubernetes.io/metadata.name: minio
          podSelector:
            matchLabels:
              app: minio
      ports:
        - protocol: TCP
          port: 9000
{{- end }} 