apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: data-service
  labels:
    app: data-service
    release: monitoring
spec:
  selector:
    matchLabels:
      app: data-service
  namespaceSelector:
    matchNames:
      - app
  endpoints:
    - port: http
      interval: 15s
      path: /metrics 