apiVersion: v1
kind: Service
metadata:
  name: data-service
  labels:
    app: data-service
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 80
      targetPort: 5678
      protocol: TCP
      name: http
  selector:
    app: data-service 