apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.credentials.secretName }}
  namespace: minio
  labels:
    app: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
type: Opaque
data:
  accesskey: {{ .Values.credentials.accessKey | b64enc }}
  secretkey: {{ .Values.credentials.secretKey | b64enc }} 