replicaCount: 1

image:
  repository: minio/minio
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 9000
  consolePort: 9001

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

persistence:
  enabled: true
  size: 10Gi
  storageClass: "standard"

securityContext:
  runAsUser: 1000
  runAsGroup: 1000
  fsGroup: 1000

# MinIO credentials
credentials:
  secretName: minio-credentials
  accessKey: minioadmin
  secretKey: minioadmin

# Bucket configuration
buckets:
  - name: data-service-bucket
    policy: |
      {
        "Version": "2012-10-17",
        "Statement": [
          {
            "Effect": "Allow",
            "Principal": {
              "AWS": ["*"]
            },
            "Action": [
              "s3:GetObject",
              "s3:PutObject",
              "s3:ListBucket"
            ],
            "Resource": [
              "arn:aws:s3:::data-service-bucket/*",
              "arn:aws:s3:::data-service-bucket"
            ]
          }
        ]
      }

# Network policy configuration
networkPolicy:
  enabled: true
  ingress:
    - from:
        - namespaceSelector:
            matchLabels:
              name: app
          podSelector:
            matchLabels:
              app: data-service
      ports:
        - protocol: TCP
          port: 9000 